<!DOCTYPE html>
  <head>
    <title>Manejo de Errores</title>
  </head>
  <body>
    <script>
      /*
      //Callbacks
      function sumar(a, b, callback){
        setTimeout(function(){
          if(typeof a != "number" || typeof b != "number"){
            return callback(new Error("Algun argumento no es un numero"))
          }
          callback(null, a+b);
        },1000)
      }
      sumar(1, 2, function(error,resultado){
        if(error){
          console.error(error);
        } else {
          console.log(resultado);
        }
        
      })
      
      
      //Promesas
      function sumar(a,b){
        return new Promise(function(resolve,reject){
          setTimeout(function(){
            if(typeof a != "number" || typeof b != "number"){
            reject(new Error("Ambos argumentos deben ser numeros"));
          } else{
            resolve(a+b);
          }
        },1000)
        })
      }
      sumar(1,2)
      .then(function(resultado){
        console.log(resultado);
      })
      .catch(function(error){
        console.error(error);
      })
      */
      
      //Async/Await
      async function sumar(a,b){
        if(typeof a != "number" || typeof b != "number"){
          throw new Error("Ambos argumentos deben ser numeros");
        }
        return a + b;
      }

      async function manejarError(){
        try{
          let resultado = await sumar(3,2);
          console.log(resultado);
        }catch(error){
          console.error(error.message);
        }
      }

      manejarError();
      
      
    </script>
  </body>
</html>